package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func runInitCmd(args []string) {
	fmt.Println("========================================")
	fmt.Println("🌱 Welcome to OpenTendril Setup Wizard! ")
	fmt.Println("========================================")

	scanner := bufio.NewScanner(os.Stdin)

	// Step 1: Detect Ollama
	fmt.Println("\n🔍 Scanning for local LLM providers...")
	ollamaModels := getOllamaModels()

	defaultProvider := "anthropic"
	localModel := ""
	inferenceURL := ""

	if len(ollamaModels) > 0 {
		fmt.Printf("✅ Detected local Ollama instance with %d models.\n", len(ollamaModels))
		fmt.Println("Would you like to use Ollama for local execution? (y/n)")
		fmt.Print("> ")
		if scanner.Scan() {
			ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
			if ans == "y" || ans == "yes" {
				defaultProvider = "local"
				inferenceURL = "http://localhost:11434/v1"
				localModel = selectOllamaModel(ollamaModels)
			}
		}
	} else {
		fmt.Println("❌ No local Ollama instance detected.")
	}

	// If they didn't choose local, let's ask about cloud
	var cloudEnvLine string
	if defaultProvider != "local" {
		fmt.Println("\n☁️  Cloud Provider Selection")
		fmt.Println("Which cloud provider would you like to use?")
		fmt.Println("1) Anthropic (Claude 3.5 Sonnet/Opus)")
		fmt.Println("2) OpenAI (GPT-4o)")
		fmt.Println("3) xAI (Grok)")
		fmt.Println("4) Google (Gemini)")
		fmt.Println("5) OpenTendril Free Trial")
		fmt.Print("Enter number (1-5): ")

		if scanner.Scan() {
			choice := strings.TrimSpace(scanner.Text())
			switch choice {
			case "1":
				defaultProvider = "anthropic"
				fmt.Print("Enter ANTHROPIC_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "ANTHROPIC_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "2":
				defaultProvider = "openai"
				fmt.Print("Enter OPENAI_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "OPENAI_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "3":
				defaultProvider = "grok"
				fmt.Print("Enter GROK_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "GROK_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "4":
				defaultProvider = "google"
				fmt.Print("Enter GOOGLE_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "GOOGLE_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "5":
				defaultProvider = "opentendril"
				cloudEnvLine = "OPENTENDRIL_API_KEY=free-trial"
			default:
				defaultProvider = "anthropic"
				fmt.Println("Invalid choice, defaulting to anthropic.")
			}
		}
	}

	// Step 2: Write Configuration
	fmt.Println("\n💾 Saving Configuration...")

	// Determine paths
	homeDir, _ := os.UserHomeDir()
	configDir := filepath.Join(homeDir, ".config", "opentendril")
	os.MkdirAll(configDir, 0755)

	envPath := filepath.Join(configDir, ".env")

	// Try to write to current directory's core/.env if it exists (for dev mode)
	if _, err := os.Stat("core/.env"); err == nil {
		envPath = "core/.env"
	} else if _, err := os.Stat(".env"); err == nil {
		envPath = ".env"
	}

	file, err := os.OpenFile(envPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		fmt.Printf("❌ Failed to open .env file: %v\n", err)
	} else {
		defer file.Close()
		file.WriteString("\n# Auto-generated by tendril init\n")
		file.WriteString(fmt.Sprintf("DEFAULT_LLM_PROVIDER=%s\n", defaultProvider))
		if defaultProvider == "local" {
			file.WriteString(fmt.Sprintf("LOCAL_INFERENCE_URL=%s\n", inferenceURL))
			file.WriteString(fmt.Sprintf("LOCAL_MODEL_NAME=%s\n", localModel))
		}
		if cloudEnvLine != "" {
			file.WriteString(cloudEnvLine + "\n")
		}
		fmt.Printf("✅ Saved to %s\n", envPath)
	}

	// Step 3: Print MCP integration guide
	fmt.Println("\n🔌 MCP Integration Guide")
	fmt.Println("To connect Antigravity (or Claude Desktop) to OpenTendril, add the following to your MCP configuration file:")
	fmt.Println("For Antigravity, edit: ~/.gemini/config/mcp_config.json")
	fmt.Println("\n{")
	fmt.Println(`  "mcpServers": {`)
	fmt.Println(`    "opentendril": {`)
	fmt.Printf(`      "command": "%s",`+"\n", filepath.Join(homeDir, ".local", "bin", "tendril"))
	fmt.Println(`      "args": ["mcp"],`)
	fmt.Println(`      "env": {}`)
	fmt.Println(`    }`)
	fmt.Println(`  }`)
	fmt.Println("}")
	fmt.Println("\n🎉 Setup Complete! You can now run `tendril chat` to start coding, or restart your IDE to enable the MCP connection.")
}

func getOllamaModels() []string {
	client := http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get("http://localhost:11434/api/tags")
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil
	}

	var data struct {
		Models []struct {
			Name string `json:"name"`
		} `json:"models"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return nil
	}

	var models []string
	for _, m := range data.Models {
		models = append(models, m.Name)
	}
	return models
}

func selectOllamaModel(models []string) string {
	// Try to auto-detect the best coding model
	for _, m := range models {
		if strings.Contains(strings.ToLower(m), "coder") {
			return m
		}
	}
	// Fallback to first model
	if len(models) > 0 {
		return models[0]
	}
	return ""
}
