package mesh

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	defaultIssuer      = "opentendril-mesh"
	defaultSubject     = "stem-graft"
	defaultAudience    = "mesh-graft"
	defaultMeshScope   = "mesh-graft"
	defaultTokenTTL    = time.Hour
	privateKeyFileName = "mesh-private-key.pem"
	publicKeyFileName  = "mesh-public-key.pem"
	jwtType            = "JWT"
	jwtAlgorithmEdDSA  = "EdDSA"
	securityDirName    = ".tendril"
	securityFolderName = "security"
)

var (
	ErrMissingPrivateKey = errors.New("mesh private key is missing")
	ErrMissingPublicKey  = errors.New("mesh public key is missing")
	ErrInvalidToken      = errors.New("invalid mesh token")
	ErrInvalidSignature  = errors.New("invalid mesh token signature")
	ErrExpiredToken      = errors.New("mesh token has expired")
	ErrNotYetValid       = errors.New("mesh token is not yet valid")
)

// KeyPair stores the Ed25519 key material used by the mesh network.
type KeyPair struct {
	PublicKey  ed25519.PublicKey
	PrivateKey ed25519.PrivateKey
}

// TokenOptions controls the JWT payload generated by the mesh signer.
type TokenOptions struct {
	Issuer        string
	Subject       string
	Audience      []string
	MeshScope     string
	WorkspacePath string
	TokenID       string
	ExpiresIn     time.Duration
	Now           time.Time
}

// TokenValidationOptions controls semantic checks applied after signature verification.
type TokenValidationOptions struct {
	Now               time.Time
	ExpectedIssuer    string
	ExpectedAudience  string
	ExpectedScope     string
	ExpectedWorkspace string
}

// TokenClaims is the signed JWT body exchanged between local and central stems.
type TokenClaims struct {
	Issuer        string   `json:"iss,omitempty"`
	Subject       string   `json:"sub,omitempty"`
	Audience      []string `json:"aud,omitempty"`
	IssuedAt      int64    `json:"iat,omitempty"`
	ExpiresAt     int64    `json:"exp,omitempty"`
	NotBefore     int64    `json:"nbf,omitempty"`
	ID            string   `json:"jti,omitempty"`
	MeshScope     string   `json:"meshScope,omitempty"`
	WorkspacePath string   `json:"workspacePath,omitempty"`
}

type jwtHeader struct {
	Algorithm string `json:"alg"`
	Type      string `json:"typ"`
}

// WorkspaceSecurityDir resolves the mesh security directory for a workspace.
func WorkspaceSecurityDir(workspace string) string {
	workspace = normalizeWorkspace(workspace)
	return filepath.Join(workspace, securityDirName, securityFolderName)
}

// WorkspaceKeyPaths resolves the private and public key file paths for a workspace.
func WorkspaceKeyPaths(workspace string) (string, string) {
	securityDir := WorkspaceSecurityDir(workspace)
	return filepath.Join(securityDir, privateKeyFileName), filepath.Join(securityDir, publicKeyFileName)
}

// GenerateKeyPair creates a fresh Ed25519 keypair for mesh signing.
func GenerateKeyPair() (KeyPair, error) {
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return KeyPair{}, fmt.Errorf("generate ed25519 keypair: %w", err)
	}

	return KeyPair{PublicKey: publicKey, PrivateKey: privateKey}, nil
}

// WriteKeyPair stores the keypair in .tendril/security using PEM encoding.
func WriteKeyPair(workspace string, pair KeyPair) error {
	securityDir := WorkspaceSecurityDir(workspace)
	if err := os.MkdirAll(securityDir, 0o755); err != nil {
		return fmt.Errorf("create mesh security directory: %w", err)
	}

	privateKeyPath, publicKeyPath := WorkspaceKeyPaths(workspace)

	privatePEM, err := encodePrivateKeyPEM(pair.PrivateKey)
	if err != nil {
		return err
	}
	if err := os.WriteFile(privateKeyPath, privatePEM, 0o600); err != nil {
		return fmt.Errorf("write mesh private key: %w", err)
	}

	publicPEM, err := encodePublicKeyPEM(pair.PublicKey)
	if err != nil {
		return err
	}
	if err := os.WriteFile(publicKeyPath, publicPEM, 0o644); err != nil {
		return fmt.Errorf("write mesh public key: %w", err)
	}

	return nil
}

// LoadKeyPair reads the Ed25519 mesh keypair from disk.
func LoadKeyPair(workspace string) (KeyPair, error) {
	privateKey, err := LoadPrivateKey(workspace)
	if err != nil {
		return KeyPair{}, err
	}

	publicKey, err := LoadPublicKey(workspace)
	if err != nil {
		return KeyPair{}, err
	}

	return KeyPair{
		PublicKey:  publicKey,
		PrivateKey: privateKey,
	}, nil
}

// LoadPrivateKey reads the private key from the workspace security directory.
func LoadPrivateKey(workspace string) (ed25519.PrivateKey, error) {
	privateKeyPath, _ := WorkspaceKeyPaths(workspace)
	payload, err := os.ReadFile(privateKeyPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("%w: %s", ErrMissingPrivateKey, privateKeyPath)
		}
		return nil, fmt.Errorf("read mesh private key: %w", err)
	}

	block, _ := pem.Decode(payload)
	if block == nil {
		return nil, fmt.Errorf("decode mesh private key pem: %w", ErrInvalidToken)
	}

	parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse mesh private key: %w", err)
	}

	privateKey, ok := parsed.(ed25519.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("mesh private key is not ed25519")
	}

	return privateKey, nil
}

// LoadPublicKey reads the public key from the workspace security directory.
func LoadPublicKey(workspace string) (ed25519.PublicKey, error) {
	_, publicKeyPath := WorkspaceKeyPaths(workspace)
	payload, err := os.ReadFile(publicKeyPath)
	if err != nil {
		if os.IsNotExist(err) {
			privateKey, privateErr := LoadPrivateKey(workspace)
			if privateErr != nil {
				return nil, fmt.Errorf("%w: %s", ErrMissingPublicKey, publicKeyPath)
			}
			return privateKey.Public().(ed25519.PublicKey), nil
		}
		return nil, fmt.Errorf("read mesh public key: %w", err)
	}

	block, _ := pem.Decode(payload)
	if block == nil {
		return nil, fmt.Errorf("decode mesh public key pem: %w", ErrInvalidToken)
	}

	parsed, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse mesh public key: %w", err)
	}

	publicKey, ok := parsed.(ed25519.PublicKey)
	if !ok {
		return nil, fmt.Errorf("mesh public key is not ed25519")
	}

	return publicKey, nil
}

// IssueWorkspaceToken loads the private key for a workspace and signs a JWT.
func IssueWorkspaceToken(workspace string, opts TokenOptions) (string, error) {
	privateKey, err := LoadPrivateKey(workspace)
	if err != nil {
		return "", err
	}

	if strings.TrimSpace(opts.WorkspacePath) == "" {
		opts.WorkspacePath = normalizeWorkspace(workspace)
	}

	return IssueToken(privateKey, opts)
}

// IssueToken signs a JWT using the supplied private key.
func IssueToken(privateKey ed25519.PrivateKey, opts TokenOptions) (string, error) {
	if len(privateKey) != ed25519.PrivateKeySize {
		return "", fmt.Errorf("invalid mesh private key length: %d", len(privateKey))
	}

	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	} else {
		now = now.UTC()
	}

	ttl := opts.ExpiresIn
	if ttl <= 0 {
		ttl = defaultTokenTTL
	}

	claims := TokenClaims{
		Issuer:        strings.TrimSpace(opts.Issuer),
		Subject:       strings.TrimSpace(opts.Subject),
		Audience:      normalizeAudience(opts.Audience),
		IssuedAt:      now.Unix(),
		ExpiresAt:     now.Add(ttl).Unix(),
		ID:            strings.TrimSpace(opts.TokenID),
		MeshScope:     strings.TrimSpace(opts.MeshScope),
		WorkspacePath: strings.TrimSpace(opts.WorkspacePath),
	}

	if claims.Issuer == "" {
		claims.Issuer = defaultIssuer
	}
	if claims.Subject == "" {
		claims.Subject = defaultSubject
	}
	if len(claims.Audience) == 0 {
		claims.Audience = []string{defaultAudience}
	}
	if claims.MeshScope == "" {
		claims.MeshScope = defaultMeshScope
	}
	if claims.ID == "" {
		claims.ID = randomTokenID()
	}

	header := jwtHeader{
		Algorithm: jwtAlgorithmEdDSA,
		Type:      jwtType,
	}

	headerBytes, err := json.Marshal(header)
	if err != nil {
		return "", fmt.Errorf("encode jwt header: %w", err)
	}

	claimsBytes, err := json.Marshal(claims)
	if err != nil {
		return "", fmt.Errorf("encode jwt claims: %w", err)
	}

	encodedHeader := base64.RawURLEncoding.EncodeToString(headerBytes)
	encodedClaims := base64.RawURLEncoding.EncodeToString(claimsBytes)
	signingInput := encodedHeader + "." + encodedClaims
	signature := ed25519.Sign(privateKey, []byte(signingInput))

	return signingInput + "." + base64.RawURLEncoding.EncodeToString(signature), nil
}

// VerifyWorkspaceToken loads the workspace public key and verifies the JWT.
func VerifyWorkspaceToken(workspace, token string, opts TokenValidationOptions) (TokenClaims, error) {
	publicKey, err := LoadPublicKey(workspace)
	if err != nil {
		return TokenClaims{}, err
	}

	return VerifyToken(token, publicKey, opts)
}

// VerifyToken validates a JWT signature and applies optional semantic checks.
func VerifyToken(token string, publicKey ed25519.PublicKey, opts TokenValidationOptions) (TokenClaims, error) {
	if len(publicKey) != ed25519.PublicKeySize {
		return TokenClaims{}, fmt.Errorf("invalid mesh public key length: %d", len(publicKey))
	}

	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return TokenClaims{}, ErrInvalidToken
	}

	headerBytes, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return TokenClaims{}, fmt.Errorf("%w: decode header: %v", ErrInvalidToken, err)
	}

	var header jwtHeader
	if err := json.Unmarshal(headerBytes, &header); err != nil {
		return TokenClaims{}, fmt.Errorf("%w: parse header: %v", ErrInvalidToken, err)
	}
	if header.Algorithm != jwtAlgorithmEdDSA {
		return TokenClaims{}, fmt.Errorf("%w: unsupported algorithm %q", ErrInvalidToken, header.Algorithm)
	}
	if strings.TrimSpace(header.Type) != "" && header.Type != jwtType {
		return TokenClaims{}, fmt.Errorf("%w: unsupported token type %q", ErrInvalidToken, header.Type)
	}

	claimsBytes, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return TokenClaims{}, fmt.Errorf("%w: decode claims: %v", ErrInvalidToken, err)
	}

	var claims TokenClaims
	if err := json.Unmarshal(claimsBytes, &claims); err != nil {
		return TokenClaims{}, fmt.Errorf("%w: parse claims: %v", ErrInvalidToken, err)
	}

	signature, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		return TokenClaims{}, fmt.Errorf("%w: decode signature: %v", ErrInvalidToken, err)
	}
	if len(signature) != ed25519.SignatureSize {
		return TokenClaims{}, ErrInvalidToken
	}

	signingInput := parts[0] + "." + parts[1]
	if !ed25519.Verify(publicKey, []byte(signingInput), signature) {
		return TokenClaims{}, ErrInvalidSignature
	}

	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	} else {
		now = now.UTC()
	}

	if claims.NotBefore != 0 && now.Unix() < claims.NotBefore {
		return TokenClaims{}, ErrNotYetValid
	}
	if claims.ExpiresAt != 0 && now.Unix() > claims.ExpiresAt {
		return TokenClaims{}, ErrExpiredToken
	}
	if expected := strings.TrimSpace(opts.ExpectedIssuer); expected != "" && claims.Issuer != expected {
		return TokenClaims{}, fmt.Errorf("%w: issuer mismatch", ErrInvalidToken)
	}
	if expected := strings.TrimSpace(opts.ExpectedAudience); expected != "" && !containsString(claims.Audience, expected) {
		return TokenClaims{}, fmt.Errorf("%w: audience mismatch", ErrInvalidToken)
	}
	if expected := strings.TrimSpace(opts.ExpectedScope); expected != "" && claims.MeshScope != expected {
		return TokenClaims{}, fmt.Errorf("%w: scope mismatch", ErrInvalidToken)
	}
	if expected := strings.TrimSpace(opts.ExpectedWorkspace); expected != "" && claims.WorkspacePath != expected {
		return TokenClaims{}, fmt.Errorf("%w: workspace mismatch", ErrInvalidToken)
	}

	return claims, nil
}

// PublicKeyFingerprint returns a short checksum that is useful for CLI output.
func PublicKeyFingerprint(publicKey ed25519.PublicKey) string {
	sum := sha256.Sum256(publicKey)
	return hex.EncodeToString(sum[:8])
}

func encodePrivateKeyPEM(privateKey ed25519.PrivateKey) ([]byte, error) {
	if len(privateKey) != ed25519.PrivateKeySize {
		return nil, fmt.Errorf("invalid mesh private key length: %d", len(privateKey))
	}

	der, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		return nil, fmt.Errorf("marshal mesh private key: %w", err)
	}

	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), nil
}

func encodePublicKeyPEM(publicKey ed25519.PublicKey) ([]byte, error) {
	if len(publicKey) != ed25519.PublicKeySize {
		return nil, fmt.Errorf("invalid mesh public key length: %d", len(publicKey))
	}

	der, err := x509.MarshalPKIXPublicKey(publicKey)
	if err != nil {
		return nil, fmt.Errorf("marshal mesh public key: %w", err)
	}

	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), nil
}

func normalizeWorkspace(workspace string) string {
	workspace = strings.TrimSpace(workspace)
	if workspace == "" {
		return "."
	}
	return workspace
}

// ResolveRepoRoot resolves the top-level git repository path for the input path.
func ResolveRepoRoot(path string) string {
	path = normalizeWorkspace(path)

	cmd := exec.Command("git", "-C", path, "rev-parse", "--show-toplevel")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return path
	}

	root := strings.TrimSpace(string(output))
	if root == "" {
		return path
	}

	return root
}

func normalizeAudience(audience []string) []string {
	if len(audience) == 0 {
		return nil
	}

	normalized := make([]string, 0, len(audience))
	seen := make(map[string]struct{}, len(audience))
	for _, raw := range audience {
		value := strings.TrimSpace(raw)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		normalized = append(normalized, value)
	}

	if len(normalized) == 0 {
		return nil
	}

	return normalized
}

func containsString(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func randomTokenID() string {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err == nil {
		return hex.EncodeToString(raw[:])
	}

	return fmt.Sprintf("mesh-%d", time.Now().UTC().UnixNano())
}
