package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

func runInitCmd(args []string) {
	fmt.Println("========================================")
	fmt.Println("🌱 Welcome to OpenTendril Setup Wizard! ")
	fmt.Println("========================================")

	scanner := bufio.NewScanner(os.Stdin)

	// Step 1: Detect Ollama
	fmt.Println("\n🔍 Scanning for local LLM providers...")
	ollamaModels := getOllamaModels()

	defaultProvider := "anthropic"
	localModel := ""
	inferenceURL := ""

	if len(ollamaModels) > 0 {
		fmt.Printf("✅ Detected local Ollama with %d model(s):\n", len(ollamaModels))
		for i, m := range ollamaModels {
			fmt.Printf("  %d) %s\n", i+1, m)
		}
		fmt.Println("Would you like to use Ollama for local, private execution? (y/n)")
		fmt.Print("> ")
		if scanner.Scan() {
			ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
			if ans == "y" || ans == "yes" {
				defaultProvider = "local"
				// Use host.docker.internal so the Docker Tendril container can reach Ollama on the host
				inferenceURL = "http://host.docker.internal:11434/v1"
				localModel = selectOllamaModel(ollamaModels)
				// Let user override model choice
				fmt.Printf("Auto-selected model: %s\n", localModel)
				fmt.Printf("Press Enter to use it, or type a different model name: ")
				if scanner.Scan() {
					if override := strings.TrimSpace(scanner.Text()); override != "" {
						localModel = override
					}
				}
				fmt.Printf("✅ Using Ollama model: %s\n", localModel)
			}
		}
	} else {
		fmt.Println("ℹ️  No local Ollama instance detected at localhost:11434.")
		fmt.Println("   Start Ollama with: ollama serve")
	}

	// If they didn't choose local, let's ask about cloud
	var cloudEnvLine string
	if defaultProvider != "local" {
		fmt.Println("\n☁️  Cloud Provider Selection")
		fmt.Println("Which cloud provider would you like to use?")
		fmt.Println("1) Anthropic (Claude 3.5 Sonnet/Opus)")
		fmt.Println("2) OpenAI (GPT-4o)")
		fmt.Println("3) xAI (Grok)")
		fmt.Println("4) Google (Gemini)")
		fmt.Println("5) OpenTendril Free Trial")
		fmt.Print("Enter number (1-5): ")

		if scanner.Scan() {
			choice := strings.TrimSpace(scanner.Text())
			switch choice {
			case "1":
				defaultProvider = "anthropic"
				fmt.Print("Enter ANTHROPIC_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "ANTHROPIC_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "2":
				defaultProvider = "openai"
				fmt.Print("Enter OPENAI_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "OPENAI_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "3":
				defaultProvider = "grok"
				fmt.Print("Enter GROK_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "GROK_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "4":
				defaultProvider = "google"
				fmt.Print("Enter GOOGLE_API_KEY: ")
				if scanner.Scan() {
					cloudEnvLine = "GOOGLE_API_KEY=" + strings.TrimSpace(scanner.Text())
				}
			case "5":
				defaultProvider = "opentendril"
				cloudEnvLine = "OPENTENDRIL_API_KEY=free-trial"
			default:
				defaultProvider = "anthropic"
				fmt.Println("Invalid choice, defaulting to anthropic.")
			}
		}
	}

	// Step 2: Write Configuration
	fmt.Println("\n💾 Saving Configuration...")

	// Determine paths
	homeDir, _ := os.UserHomeDir()
	configDir := filepath.Join(homeDir, ".config", "opentendril")
	os.MkdirAll(configDir, 0755)

	envPath := filepath.Join(configDir, ".env")

	// Try to write to current directory's core/.env if it exists (for dev mode)
	if _, err := os.Stat("core/.env"); err == nil {
		envPath = "core/.env"
	} else if _, err := os.Stat(".env"); err == nil {
		envPath = ".env"
	}

	file, err := os.OpenFile(envPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		fmt.Printf("❌ Failed to open .env file: %v\n", err)
	} else {
		defer file.Close()
		file.WriteString("\n# Auto-generated by tendril init\n")
		file.WriteString(fmt.Sprintf("DEFAULT_LLM_PROVIDER=%s\n", defaultProvider))
		if defaultProvider == "local" {
			file.WriteString(fmt.Sprintf("LOCAL_INFERENCE_URL=%s\n", inferenceURL))
			file.WriteString(fmt.Sprintf("LOCAL_MODEL_NAME=%s\n", localModel))
		}
		if cloudEnvLine != "" {
			file.WriteString(cloudEnvLine + "\n")
		}
		fmt.Printf("✅ Saved to %s\n", envPath)
	}

	// Step 3: Print next steps
	homeBin := filepath.Join(homeDir, ".local", "bin", "tendril")
	fmt.Println()
	fmt.Println("════════════════════════════════════════")
	fmt.Println("  🎉 OpenTendril Setup Complete!")
	fmt.Println("════════════════════════════════════════")
	if defaultProvider == "local" {
		fmt.Printf("  Provider : Ollama (local, private)\n")
		fmt.Printf("  Model    : %s\n", localModel)
		fmt.Printf("  URL      : %s\n", inferenceURL)
	} else {
		fmt.Printf("  Provider : %s\n", defaultProvider)
	}
	fmt.Println()
	fmt.Println("  Next steps:")
	fmt.Println("  1. Start the Stem server:   tendril serve")
	fmt.Println("  2. Chat in a new terminal:  tendril chat")
	fmt.Println()
	fmt.Println("  MCP Integration (for Antigravity / Claude Desktop):")
	fmt.Println("  Edit: ~/.gemini/config/mcp_config.json")
	fmt.Println("  Add:")
	fmt.Printf("    {\"mcpServers\": {\"opentendril\": {\"command\": \"%s\", \"args\": [\"mcp\"]}}}\n", homeBin)
	fmt.Println("════════════════════════════════════════")

	go func() {
		cmd := exec.Command("docker", "pull", "opentendril-typescript:latest")
		_ = cmd.Start()
	}()
}

func getOllamaModels() []string {
	client := http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get("http://localhost:11434/api/tags")
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil
	}

	var data struct {
		Models []struct {
			Name string `json:"name"`
		} `json:"models"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return nil
	}

	var models []string
	for _, m := range data.Models {
		models = append(models, m.Name)
	}
	return models
}

func selectOllamaModel(models []string) string {
	// Try to auto-detect the best coding model
	for _, m := range models {
		if strings.Contains(strings.ToLower(m), "coder") {
			return m
		}
	}
	// Fallback to first model
	if len(models) > 0 {
		return models[0]
	}
	return ""
}
