package main

import (
	"fmt"
	"os"

	"github.com/opentendril/opentendril/cmd/stem/internal/substrateconfig"
	"gopkg.in/yaml.v3"
)

// Merge/append mode for `tendril git setup`. A deployment has multiple
// repositories, so re-running setup must be additive: upsert this run's
// entries into an existing substrates.yaml while preserving every other entry
// AND the user's comments and formatting. The work is done on the YAML node
// tree (a surgical insert/update) rather than by re-marshalling typed structs,
// so hand-edits survive intact.
//
// Rules:
//   - A new named entry (credential profile, substrate) is added freely.
//   - An existing named entry is overwritten only with --force (otherwise a
//     clear error) — a specific connection is never silently replaced.

// upsertSubstrates applies this run's connection through the shared persistent
// Substrate-registry mutation service. The service selects the canonical path's
// legacy import behavior and performs validated atomic replacement.
func upsertSubstrates(path string, o gitSetupOptions) error {
	result, err := substrateconfig.Mutate(path, func(root *yaml.Node) error {
		return mergeConnectionNode(root, o)
	})
	if err != nil {
		return err
	}
	if result.ImportedLegacy {
		fmt.Fprintf(os.Stderr, "🌱 Imported legacy registry %s into %s\n", result.Source, result.Destination)
	}
	if result.LegacyIgnored {
		fmt.Fprintf(os.Stderr, "ℹ️  Ignored legacy registry %s; canonical registry is active\n", result.LegacyPath)
	}
	if result.Created {
		fmt.Fprintf(os.Stderr, "🌱 Wrote %s\n", result.Destination)
	} else {
		fmt.Fprintf(os.Stderr, "🌱 Updated %s (connection %q)\n", result.Destination, o.substrate)
	}
	return nil
}

// mapValue returns the value node for key within mapping m and the value's
// index in m.Content, or (nil, -1) when the key is absent.
func mapValue(m *yaml.Node, key string) (*yaml.Node, int) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1], i + 1
		}
	}
	return nil, -1
}

func scalarNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

// getOrCreateMapping returns the mapping value for key under m, creating an
// empty mapping (and its key) when absent.
func getOrCreateMapping(m *yaml.Node, key string) (*yaml.Node, error) {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("registry node for %q is not a mapping", key)
	}
	if v, _ := mapValue(m, key); v != nil {
		if v.Kind != yaml.MappingNode {
			return nil, fmt.Errorf("registry entry %q is not a mapping", key)
		}
		return v, nil
	}
	v := &yaml.Node{Kind: yaml.MappingNode}
	m.Content = append(m.Content, scalarNode(key), v)
	return v, nil
}

// setMapEntry upserts key->value in m; an existing key is replaced only when
// force is set, otherwise it errors so a specific entry is never clobbered.
func setMapEntry(m *yaml.Node, key string, value *yaml.Node, force bool) error {
	if v, idx := mapValue(m, key); v != nil {
		if !force {
			return fmt.Errorf("%q already exists (pass --force to update it)", key)
		}
		m.Content[idx] = value
		return nil
	}
	m.Content = append(m.Content, scalarNode(key), value)
	return nil
}

// parseMappingFragment parses a YAML fragment into its top-level mapping node,
// used to turn a rendered value block into a node ready to insert.
func parseMappingFragment(fragment string) (*yaml.Node, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(fragment), &doc); err != nil {
		return nil, err
	}
	if len(doc.Content) == 0 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("rendered fragment is not a mapping")
	}
	return doc.Content[0], nil
}

// mergeConnection upserts the run's credential profile and substrate into an
// existing substrates.yaml, preserving every other entry.
func mergeConnection(path string, o gitSetupOptions) error {
	_, err := substrateconfig.Mutate(path, func(root *yaml.Node) error {
		return mergeConnectionNode(root, o)
	})
	return err
}

func mergeConnectionNode(root *yaml.Node, o gitSetupOptions) error {
	if len(root.Content) == 0 {
		root.HeadComment = "Generated by `tendril git setup`. Secrets are referenced by env-var name\nor key path, never stored here. Edit freely; re-run setup to regenerate."
	}
	profile := o.substrate + "-connection"
	profileNode, err := parseMappingFragment(renderProfileValueYAML(o))
	if err != nil {
		return err
	}
	credentials, err := getOrCreateMapping(root, "credentials")
	if err != nil {
		return err
	}
	if err := setMapEntry(credentials, profile, profileNode, o.force); err != nil {
		return fmt.Errorf("credentials.%s: %w", profile, err)
	}
	substrateNode, err := parseMappingFragment(renderSubstrateValueYAML(o))
	if err != nil {
		return err
	}
	substrates, err := getOrCreateMapping(root, "substrates")
	if err != nil {
		return err
	}
	if err := setMapEntry(substrates, o.substrate, substrateNode, o.force); err != nil {
		return fmt.Errorf("substrates.%s: %w", o.substrate, err)
	}
	return nil
}
